version: '3.3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    #command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=3000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
        - ./db/storage:/var/lib/postgresql/data
    ports:
        - "55432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres